### ISSUE TITLE
allow values

### ISSUE THREAD

**Issue by zapphyre** [AntJanus/JSON-structure-validator#6]
Hi,
would that be too complicated for you to allow object keys to have a values present? Maybe there can be some switch to allow this..
This would help in further assertions.

**Comment by AntJanus** [comment]
Basically to check not only the structure but also values? 

I'm currently working on a "reboot" of this repo over here: https://github.com/asteridux/skorice

Right now, the values of the template keys can be used against value typing. I'm planning to expand some of this functionality.

**Comment by zapphyre** [comment]
no, I mean just to allow response template to have a values, not just empty strings as keys values.
currently if you do so, you'll get an exception:
```

RangeError: Maximum call stack size exceeded
    at keys.forEach (node_modules/json-structure-validator/lib/json-structure-validator.js:6:16)
    at Array.forEach (<anonymous>)
```

to have values in the response template would enable me to make furthe value-based assertions.

**Comment by AntJanus** [comment]
Hmm, I'll label this as a bug. You should be able to pass in whatever you want, not just empty strings

**Comment by zapphyre** [comment]
try for yourself, please;

**Comment by AntJanus** [comment]
@zapphyre I wasn't able to reproduce the bug but I did add a new test to test the behavior: https://github.com/AntJanus/JSON-structure-validator/blob/master/__tests__/validator.test.js#L72

Can you tell me how your example differs? Looking at the error now, it might have been caused by an object that possibly nests very deeply which would cause that call stack size error due to recursion. I'm going to keep this open, looks like the issue is due to how the recursive function works.

**Comment by zapphyre** [comment]
differs not much. I use very simple structures like 
```
{
  "dms$partyId": "qwer",
  "dms$folderId": "asd124"
}
```

and I still getting endless stackrace of 

```
Uncaught RangeError: Maximum call stack size exceeded
      at Array.forEach (native)
      at compareJSON (node_modules/json-structure-validator/lib/json-structure-validator.js:6:8)
      at keys.forEach (node_modules/json-structure-validator/lib/json-structure-validator.js:12:23)
      at Array.forEach (native)
      at compareJSON (node_modules/json-structure-validator/lib/json-structure-validator.js:6:8)
      at keys.forEach (node_modules/json-structure-validator/lib/json-structure-validator.js:12:23)
      at Array.forEach (native)
      at compareJSON (node_modules/json-structure-validator/lib/json-structure-validator.js:6:8)
      at keys.forEach (node_modules/json-structure-validator/lib/json-structure-validator.js:12:23)
      at Array.forEach (native)
      at compareJSON (node_modules/json-structure-validator/lib/json-structure-validator.js:6:8)
      at keys.forEach (node_modules/json-structure-validator/lib/json-structure-validator.js:12:23)
      at Array.forEach (native)
```

even on the jenkins server. is it worth to mention that I am using it inside mocha test, maybe?

**Comment by AntJanus** [comment]
@zapphyre I apologize for not having been able to get back into this. i'm going to try to setup a playground on codesandbox where we can debug this. 

The problem is probably a little deeper than I realized and will have to use timeouts in order to clear the stack. That wasn't something I was counting on having to do. I looked at your data structures from the other issue and I definitely use structures that are much longer and more complicated without a problem.

Did you say that if you keep the template values empty that it works? But if the values are present, it doesn't? Did you verify that?

**Comment by AntJanus** [comment]
Check [this out](https://matthiasak.github.io/arbiter-frame/#/*%20%281%29%20code%20your%20JS%20as%20normal.%0A%20*%20%282%29%20parsing%20and%20operational%20errors%20will%20be%20displayed%20in%20a%20popover.%0A%20*%20%283%29%20CMD+S%20to%20share%20a%20link%20to%20your%20code.%0A%20*%0A%20*%20Other%20things%20to%20note%3A%20this%20tool%20compiles%20es7/6%20%28es2015/2016%29%20into%20es5%2C%20sends%20it%0A%20*%20to%20an%20iframe%2C%20and%20polyfills%20most%20missing%20functionality.%20Thus%2C%20for%20built-in%20AJAX%2C%0A%20*%20you%20can%20use%20fetch%28%29%2C%20and%20for%20built-in%20Promises%20you%20can%20use%20the%20es6%20Promise%28%29%20spec.%0A%20*%0A%20*%20What%20else%20works%20with%20Arbiter%3F%20...%20Everything%21%20Arbiter%20uses%20babel-core%20to%20transpile%0A%20*%20JavaScript%20right%20here%2C%20in%20your%20browser.%20You%20can%20see%20the%20latest%20and%0A%20*%20greatest%20Babel%20features%20at%20https%3A//babeljs.io/docs/learn-es2015/.%0A%20*%0A%20*%20require%28%29%20any%20package%20like%20so%3A%0A%20*%0A%20*%20--------%0A%20*%20require%28%27react%27%2C%20%27lodash%27%29.then%28%29%20%3D%3E%20//%20load%20multiple%20libs%2C%20too%21%0A%20*%20%20%20%20%20let%20React%20%3D%20react%0A%20*%20%20%20%20%20//%20...%20use%20React%20as%20normal%0A%20*%20%29%0A%20*%0A%20*%20or%20require%20any%20specific%20version%20with%20semver%3A%0A%20*%20require%28%27lodash@%5E3.0.1%27%29%0A%20*%20require%28%27react@0.14.1%27%29%0A%20*%20--------%0A%20*%0A%20*%20Built%20with%20love%20by%20@matthiasak%0A%20*%20-%20http%3A//mkeas.org%0A%20*%20-%20http%3A//github.com/matthiasak%0A%20*%20*/%0A%0Arequire%28%27json-structure-validator%27%29%0A%20%20.then%28%28%29%20%3D%3E%20%7B%0A%09let%20compareJSON%20%3D%20jsonStructureValidator%3B%0A%20%20%20%20%0A%20%20%20%20const%20template%20%3D%20%7B%0A%20%20%20%20%20%20%22dms%24documents%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22dms%24mchMetadata%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22pro%24productInstanceIds%22%3A%20%5B%5D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%22dms%24folderId%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22sys%24language%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22dms%24documentName%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22sys%24contentType%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22sys%24filename%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22sys%24createdBy%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22sys%24createdTs%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22sys%24modifiedBy%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22sys%24modifiedTs%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22dms%24documentState%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22dms%24validFrom%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22dms%24validTo%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22dms%24documentId%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22dms%24version%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22dms%24documentType%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22sys%24content%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22crm%24partyId%22%3A%20%22%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%3B%0A%20%20%20%20const%20testObj%20%3D%20%7B%0A%20%20%20%20%20%20%22dms%24documents%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22dms%24mchMetadata%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22pro%24productInstanceIds%22%3A%20%5B%5D%0A%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%22dms%24folderId%22%3A%20%22061bc308-574e-4c16-af79-0ded25297608%22%2C%0A%20%20%20%20%20%20%20%20%20%22sys%24language%22%3A%20%22cs%22%2C%0A%20%20%20%20%20%20%20%20%20%22dms%24documentName%22%3A%20%22Document%20Small4%22%2C%0A%20%20%20%20%20%20%09%20%22sys%24contentType%22%3A%20%22application/pdf%22%2C%0A%20%20%20%20%20%20%20%20%20%22sys%24filename%22%3A%20%22file4.pdf%22%2C%0A%20%20%20%20%20%20%20%20%20%22sys%24createdBy%22%3A%20%22jdadak%22%2C%0A%20%20%20%20%20%20%20%20%20%22sys%24createdTs%22%3A%20%222017-10-12T23%3A01%3A43.623%22%2C%0A%20%20%20%20%20%20%20%20%20%22sys%24modifiedBy%22%3A%20null%2C%0A%20%20%20%20%20%20%20%20%20%22sys%24modifiedTs%22%3A%20%222017-10-12T23%3A01%3A43.623%22%2C%0A%20%20%20%20%20%20%20%20%20%22dms%24documentState%22%3A%20%22ACTIVE%22%2C%0A%20%20%20%20%20%20%20%20%20%22dms%24validFrom%22%3A%20%222009-09-09%22%2C%0A%20%20%20%20%20%20%20%20%20%22dms%24validTo%22%3A%20%222019-02-12%22%2C%0A%20%20%20%20%20%20%20%20%20%22dms%24documentId%22%3A%20%225d784a37-e45d-4d92-96fb-18908677fed3%22%2C%0A%20%20%20%20%20%20%20%20%20%22dms%24version%22%3A%20%221.0%22%2C%0A%20%20%20%20%20%20%20%20%20%22dms%24documentType%22%3A%20%22DEPOSITINSURANCESIGNED%22%2C%0A%20%20%20%20%20%20%20%20%20%22sys%24content%22%3A%20%22YWhvago%3D%22%2C%0A%20%20%20%20%20%20%20%20%20%22crm%24partyId%22%3A%20%22PartyFop110%22%2C%0A%20%20%20%20%20%20%20%20%20%22dms%24relatedDocuments%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%22dms%24documentId%22%3A%20%22967d6a43-22d6-493a-802b-59d98acea730%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%22dms%24version%22%3A%20%221.0%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22dms%24documentName%22%3A%20%22dummyName%22%0A%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%5D%0A%20%20%20%7D%3B%0A%20%20%20%20%0A%20%20%20%20const%20bod%20%3D%20document.querySelector%28%27body%27%29%0A%20%20%20%20bod.innerHTML%20%3D%20%27Test%3A%20%27%20+%20compareJSON%28template%2C%20testObj%29%3B%0A%20%20%20%20bod.style.backgroundColor%20%3D%20%27white%27%3B%0A%0A%7D%29%3B).

**Comment by zapphyre** [comment]
you have an empty template too. I need values in it

**Comment by AntJanus** [comment]
@zapphyre nice! I got the issue to replicate, now I can test this. Thank you! :)

**Comment by AntJanus** [comment]
@zapphyre figured out the issue. I switch from using lodash to using native methods and there was a side effect I didn't expect. If you run `Object.keys()` on a string, you'll get an array of the characters in the string. Doesn't make sense at all... so I'm going to add an extra check.

**Comment by AntJanus** [comment]
@zapphyre I just did a 1.2.1 release that should fix the issue. Can you verify it on your end?

**Comment by zapphyre** [comment]
alright, it works now!
sorry for late response, you can safely close this ;)

**Comment by AntJanus** [comment]
PHEW. Thanks! I'll port this over to Skorice when I'm able to.
