### ISSUE TITLE
object comparison

### ISSUE THREAD

**Issue by zapphyre** [AntJanus/JSON-structure-validator#7]
Hi, another thing I have is that comparison of this objects has returned `true`:
```
{
  "dms$documents": [
    {
      "dms$mchMetadata": {
        "pro$productInstanceIds": []
      },
      "dms$folderId": "",
      "sys$language": "",
      "dms$documentName": "",
      "sys$contentType": "",
      "sys$filename": "",
      "sys$createdBy": "",
      "sys$createdTs": "",
      "sys$modifiedBy": "",
      "sys$modifiedTs": "",
      "dms$documentState": "",
      "dms$validFrom": "",
      "dms$validTo": "",
      "dms$documentId": "",
      "dms$version": "",
      "dms$documentType": "",
      "sys$content": "",
      "crm$partyId": ""
    }
  ]
}
```
and
```
{
  "dms$documents": [
    {
      "dms$mchMetadata": {
        "pro$productInstanceIds": []
      },
      "dms$folderId": "061bc308-574e-4c16-af79-0ded25297608",
      "sys$language": "cs",
      "dms$documentName": "Document Small4",
      "sys$contentType": "application/pdf",
      "sys$filename": "file4.pdf",
      "sys$createdBy": "jdadak",
      "sys$createdTs": "2017-10-12T23:01:43.623",
      "sys$modifiedBy": null,
      "sys$modifiedTs": "2017-10-12T23:01:43.623",
      "dms$documentState": "ACTIVE",
      "dms$validFrom": "2009-09-09",
      "dms$validTo": "2019-02-12",
      "dms$documentId": "5d784a37-e45d-4d92-96fb-18908677fed3",
      "dms$version": "1.0",
      "dms$documentType": "DEPOSITINSURANCESIGNED",
      "sys$content": "YWhvago=",
      "crm$partyId": "PartyFop110",
      "dms$relatedDocuments": [
        {
          "dms$documentId": "967d6a43-22d6-493a-802b-59d98acea730",
          "dms$version": "1.0",
          "dms$documentName": "dummyName"
        }
      ]
    }
  ]
}
```
namely, the difference which I expected to render this test failed is `"dms$relatedDocuments"`.
template is the one without values ;)

**Comment by AntJanus** [comment]
@zapphyre that's correct behavior. The template specifies the minimum required structure rather than "this is how it has to look". You'd have to do a comparison forward and backward by basically using the filled-out structure as a template and compare it against the existing template.

I've mentioned this before but I have a new library out and this confusion is why I added a `assertExact` method which will do this for you automatically.

**Comment by zapphyre** [comment]
sorry, but in the why section of the description of your lib you are using words likde 'specific', 'exactly' and I can't see any mention of minimal required. that's why I count on exact match. test's should be exactly I get what I want, I think.
so, is your new lib out? I would deffinetely like to upgrade ;)

**Comment by AntJanus** [comment]
@zapphyre https://www.npmjs.com/package/skorice here you go :)

**Comment by AntJanus** [comment]
As far as the docs:

```
Many testing frameworks allow assertion of "equals" where the resulting feed is matched EXACTLY against another feed; however, the data that comes back may change as an application evolves, the data keys may not.

The json structure validator works on a "minimum" principle, meaning that we're validating the minimum required keys.
```

The second paragraph above mentions the "minimum" part and that it's unlike other testing frameworks that test for equalness and exactness. 

At the bottom of the readme, you can read about how to get an exact match: by doing two comparisons

```js
var comparison = compareJSON(body, emptyMap);
var comparison2 = compareJSON(emptyMap, body);
```

But yeah, you're right. The docs aren't that great.
